name: Backend Build and deploy

on:
  push:
    branches:
      - main
      
jobs: 
  build:
    runs-on: ubuntu-latest
    env:
      spring.datasource.password: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17
    
    - name: Build Fat JAR
      run: |
        cd api/
        mvn package -DskipTests=true
        cd target
        pwd
    
    - name: Deploy to DigitalOcean
      uses: nogsantos/ssh-scp-deploy@master
      with:
        src: /home/runner/work/blex/blex/api/target/Blex-blex.jar
        host: ${{ secrets.SSH_HOST }}
        remote: /var/www/blex
        port: 22
        user: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
