name: Backend Build and deploy

on:
  push:
    branches:
      - main
      
jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17
    
    - name: Build Fat JAR
      run: |
        cd api/
        mvn package -DskipTests=true

    
    - name: Deploy to DigitalOcean
      uses: actions/upload-artifact@v2
      with:
        name: Blex-blex.jar
        path: api/target/Blex-blex.jar
    
    - name: Deploy to DigitalOcean
      run: |
        scp -o "StrictHostKeyChecking=no" -i ${{ secrets.SSH_KEY }} Blex-blex.jar ${{ secrets.SSH_USERNAME}}@${{ secrets.SSH_HOST }}:/var/www/blex/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
